# Generated by Django 4.0.2 on 2022-04-25 12:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='food',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
