# Generated by Django 4.0.2 on 2022-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='موجودی'),
        ),
    ]
