# Generated by Django 4.0.2 on 2022-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_read',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
