# Generated by Django 4.0.3 on 2022-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان در url')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogs', to='blog.blogtag', verbose_name='تگ ها'),
        ),
    ]
