# Generated by Django 4.0.2 on 2022-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_tags_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='BlogComments',
        ),
    ]
