# Generated by Django 4.0.2 on 2022-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
