# Generated by Django 4.0.2 on 2022-05-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='فایل ها'),
        ),
    ]
